### ISSUE TITLE
docs page not rendering

### ISSUE THREAD

**Issue by 0x00A** [datproject/website#28]
`http://dat-data.com/docs` has a [`template`](https://github.com/datproject/website/blob/master/render.js#L25) that gets used by [`renderStatic`](https://github.com/datproject/website/blob/master/render.js#L51), but [`no mustache templating is done`](https://github.com/datproject/website/blob/master/render.js#L59-L62). So the result looks like this...

![image](https://cloud.githubusercontent.com/assets/136109/12108439/da0c0418-b3b2-11e5-8004-325346f211ac.png)

I would PR but i wasn't sure if the `{{{readme}}}` data was intended to be the repo's root `readme.md` file or something else.

**Comment by 0x00A** [comment]
I also got `404` from `http://datproject.readthedocs.org/en/latest/`.

![image](https://cloud.githubusercontent.com/assets/136109/12108629/eb7cc58c-b3b4-11e5-808e-1f51f0a513f0.png)

**Comment by karissa** [comment]
thanks this is fixed!
