### ISSUE TITLE
post-commit auto deploy

### ISSUE THREAD

**Issue by clkao** [datproject/website#37]
maybe use travis with encrypted github key to push to gh-pages.

**Comment by joehand** [comment]
I set this up for our [docs site](https://github.com/datproject/docs) over the weekend. If anyone wants to learn how that works I can pair to set up this site for auto deploy!

If not I'll do it by my lonesome.

**Comment by joehand** [comment]
I guess [this happens already](https://github.com/datproject/website#deploy), never mind!
