### ISSUE TITLE
dat-data.com to datproject.org

### ISSUE THREAD

**Issue by joehand** [datproject/website#48]
We moved to datproject.org. We probably have the old domain, dat-data.com, hardcoded in places.

**Comment by Kriesse** [comment]
Shall we also update any instances of "Dat Data" to "Dat Project" in copywriting and logos? I say yes. E.g. here:

![image](https://cloud.githubusercontent.com/assets/53684/20004640/dbac3a8e-a28d-11e6-8b5a-5901ec9900a6.png)

**Comment by karissa** [comment]
Sounds good!

**Comment by juliangruber** [comment]
👍
